apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc2
  
spec:  
  replicas: 1
  selector:
    continent: Asia
    country: russia
    language: russian

  template:
    metadata:
      name: mypod
      labels:
        continent: Asia
        country: russia
        language: russian
    spec:
      containers: 
      - name: cont1
        image: httpd	

  
