apiVersion: v1
kind: ReplicationController
metadata:
  name: rc1

spec:
  replicas: 3
  selector:
    dc: mumbai
  template:
    metadata:
      name: webserver
      labels: 
        dc: mumbai
    spec:
      containers:
      - name: myweb
        image: vimal13/apache-webserver-php
